### ISSUE TITLE
Multicolour reflection Unity 2020.2.1f1 URP

### ISSUE THREAD

**Issue by addybongo** [game-ci/unity-builder#227]
**Bug description**
![image](https://user-images.githubusercontent.com/6827104/110932429-65cd9d00-8323-11eb-9836-c5510dfa7b76.png)

Reflections seem to be broken after building in GitHub actions, all reflections show this rainbow effect instead of reflecting the skybox. When I build the project manually from my Unity Editor I don't have the issue. 

**How to reproduce**

When building a project using Unity 2020.2.1f1 with a reflective/Lit shader using the Universal Render Pipeline. This is the screenshot of the shader I used:
![image](https://user-images.githubusercontent.com/6827104/110932990-12a81a00-8324-11eb-8157-880152ff7c17.png)

And this is the lighting settings used:
![image](https://user-images.githubusercontent.com/6827104/110933076-353a3300-8324-11eb-9ca6-95c9dff0f594.png)

Finally the URP settings used:
![image](https://user-images.githubusercontent.com/6827104/110933178-5438c500-8324-11eb-962a-57d0d06c58af.png)
![image](https://user-images.githubusercontent.com/6827104/110933154-4e42e400-8324-11eb-83c8-bc2a3c930358.png)

**Expected behavior**
Reflections should show the skybox like this:
![image](https://user-images.githubusercontent.com/6827104/110933221-63b80e00-8324-11eb-923c-5a452357d0dd.png)

**Comment by GabLeRoux** [comment]
That rainbow is not a bug, it's a feature 🌈 . Ok jokes apart, [which version of the game-ci/unity-builder are you using?](https://github.com/game-ci/unity-builder/releases).

To make things easier, you might also try to display the settings used directly on screen or using `Debug.Log` and something like the following unity asset: [In-game Debug Console](https://assetstore.unity.com/packages/tools/gui/in-game-debug-console-68068). I suspect that the URP settings might not be active in the result or something like that.

The problem could come from multiple places so here's what I would try in order to identify where the problem really comes from:

1. Try with a few different unity versions
2. Try to create a build from Linux directly
3. Clone the project in a new blank folder and try to build from there (if you reproduce in a brand new build, it would mean there is something that doesn't get through the repository when github-actions is building it).
4. Try to build your project from Ubuntu 18.04 with the Linux Unity editor (github-actions uses [game-ci/docker images](https://game.ci/docs/docker/docker-images) which are actually running a Linux version of the Unity editor.

Also, a few open questions:
* What does your github-actions yaml file look like?
* Could it be related to project's quality settings, did you try changing them in-game and see what happens?

**Comment by addybongo** [comment]
haha I wish it was a feature, if I don't fix it I might genuinely tell the team I hand it to that it is :joy:. 

I'm currently using v2.0-alpha-6, I'll try your possible steps now and see where its coming from. Thank you!

**Comment by webbertakken** [comment]
One more idea; check if the skybox reflection is somehow induced through global illumination (which requires gpu rendering, which does not work due to a bug in Unity that forced us to always provide the `-nographics` flag to the editor).

So, if you're able to try a different way of rendering or CPU rendering it might start working.

**Comment by addybongo** [comment]
Unfortunately I wasn't able to get this fixed and handing the project over next week, so I guess I really am shipping it as a feature :joy:.

Thank you guys for all your help anyway, I will close this issue now!
