### ISSUE TITLE
Is it possible to cache the docker image?

### ISSUE THREAD

**Issue by Razenpok** [game-ci/unity-builder#267]
Is it possible to cache built Docker image to reuse in builds?

**Comment by webbertakken** [comment]
It is indeed possible to cache the docker image after pulling it.

However, since GitHub hosted runners are using ephemeral storage, it is currently only possible for self-hosted runners.

Things to consider:
- The image is about 1.5 to 4.5GB (compressed) depending on the target platform.
- The network between DockerHub and GitHub is quite fast, so it takes about [45 seconds](https://github.com/game-ci/unity-builder/runs/2674094458?check_suite_focus=true#step:4:229) every run (caching will not make this instant).
- Caching Library folder and LFS assets will yield much bigger performance wins (be sure to cache these as well).
- Builds are quite cpu intensive and depending on your project may take a long time to build. 45 minutes may not be a very large percentage of your total build workflow time.

Hope that helps 🙂

**Comment by Razenpok** [comment]
Thank you for such an exhaustive answer! I think it's fine to have 45 sec overhead in our builds.
