### ISSUE TITLE
Import fails for Blender assets

### ISSUE THREAD

**Issue by dtrailin** [game-ci/unity-builder#268]
**Bug description**
I'm unable import blender assets because Blender is not installed in the container. 

**How to reproduce**

- Create a unity project with and import a `.blend` asset. 

**Expected behavior**
I expect the asset to import correctly during build. However, I get the error:

```
2021-05-30T16:57:28.0980276Z Start importing Assets/tri.blend using Guid(1b0313b4d58e97d48b962f87d82a4889) Importer(-1,00000000000000000000000000000000) Error: execv(blender): No such file or directory -1Blender could not be launched.
2021-05-30T16:57:28.0982236Z Make sure that Blender is installed correctly and in your PATH.
```

It would be helpful to be able to import Blender assets without being required to convert them to a different format.

**Comment by webbertakken** [comment]
Thank you for creating this issue @dtrailin.

I would consider this an enhancement instead of a bug, since we're working with an incremental approach and this is functionality that we are not yet supporting.

As I understand it, blender would have to be installed for the assets to be imported correctly. The installation is about 190MB which might be acceptable to install in the unity-editor docker image. Either way in order to support this, it would have to be fixed upstream in [game-ci/docker](https://github.com/game-ci/docker).

**Comment by GabLeRoux** [comment]
For reference, this was previously discussed here (when we were using `gableroux/unity3d` docker images):  https://gitlab.com/gableroux/unity3d-gitlab-ci-example/-/issues/19

Suggested solution should also apply here, we should document and explain how we can customize docker images to add dependencies like that. 👍

**Comment by webbertakken** [comment]
Blender assets will be supported as part of a plugin system in v3.0.0 which is tracked on the [Roadmap to v3.0.0](https://github.com/orgs/game-ci/projects/4/views/1).
