### ISSUE TITLE
AWS Fargate S3 Bucket name issue

### ISSUE THREAD

**Issue by edencakir** [game-ci/unity-builder#270]
**Bug description**
S3 bucket names should be unique but the base-setup.yml file contains hardcoded `BucketName: game-ci-storage` line which makes the template creation fail.
https://raw.githubusercontent.com/game-ci/unity-builder/main/dist/cloud-formations/base-setup.yml

**How to reproduce**
Follow the builder steps [here](https://game.ci/docs/github/remote-builder).

We should either state this in the document or automate this process in code, maybe through build step parameters?

**Comment by webbertakken** [comment]
@edencakir indeed, looks like this should be fixed on builder side.

Are you able to provide the portion of the output that contains the error?

cc: @frostebite maybe we're able to accept the suggested name for the bucket and capture the output name?

**Comment by frostebite** [comment]
Will fix.

@webbertakken agreed, will look at supporting that.

**Comment by edencakir** [comment]
@webbertakken after this event other services fail as well. changing the hardcoded value to unique string fixed the issue.
<img width="693" alt="Screen Shot 2021-06-05 at 21 52 18" src="https://user-images.githubusercontent.com/6555480/120902308-4e632f00-c648-11eb-8a6e-0948db66403c.png">

**Comment by webbertakken** [comment]
@frostebite I believe you had fixed this issue a while back already, correct?

**Comment by webbertakken** [comment]
@frostebite could you please have a look at this issue?

**Comment by frostebite** [comment]
In the release branch `cloud-runner-develop` https://game.ci/docs/github-cloud-runner/configuration#release-branch-configuration

This has been resolved. The S3 bucket was never explicitly needed, so it's been removed. This happened if you deleted the "base cloud formation" and tried to re-run cloud runner, which reinstalls the base stack if it's missing. And AWS doesn't delete the S3 bucket to protect your data by default. 

So this can also be fixed by just forcing the S3 bucket to delete and running again.

This will be in the main release branch when either of these are merged #459 #437.

Please feel welcomed to reopen a ticket @edencakir if you have any more questions or issues. 🙏
