### ISSUE TITLE
Executable permissions for Linux builds

### ISSUE THREAD

**Issue by rootools** [game-ci/unity-builder#339]
Hello.

I noticed that setting execution permissions is only for macOS builds. Perhaps it is reasonable to do this for Linux applications as well?

**Comment by GabLeRoux** [comment]
Setting execution permission on macOS builds was necessary because otherwise, the resulting build was not executable on macOS. I am not sure if this is a problem on Linux too or not, but it would be good to know if this is really an issue so we can take action.

Here are the related lines for the macOS builds:

* https://github.com/game-ci/unity-builder/blob/3d0eb0805bbe2df90e319abbe42e41d0b9105625/dist/platforms/ubuntu/steps/build.sh#L173
* https://github.com/game-ci/unity-builder/blob/c7907c7e78c756022804260141370bacda9234d5/dist/platforms/mac/steps/build.sh#L175

Do we have a confirmation that the generated binaries from Unity for Linux builds are not executable? If so, a similar command should be added for Linux in the same files as above.

**Comment by rootools** [comment]
I used to use Linux but not now. I'm not 100% sure that when transferring a file from system to system, rights are preserved. When I downloaded the Linux build on my mac, I no longer had the right to launch it. We are need confirmation from a real Linux user. Well, on the other hand, all Linux users know how to do chmod +x 🙃

**Comment by webbertakken** [comment]
I think indeed on Linux people know how to set the executable bit. And I think it's a normal step in a users workflow to do so (consciously setting it). 

I'd argue that until there is a use case where setting the bit would simplify things, we might just close this.

What do you think?
