### ISSUE TITLE
Builds failing due to missing assembly references

### ISSUE THREAD

**Issue by ottah** [game-ci/unity-builder#364]
**Bug description**
I'm trying to migrate over to using GameCI and I'm having an issue with builds failing due to missing assembly references from .dlls included in packages or included in the `Assets` folder. When building the project with the Unity editor it builds and works, the same when using a build script in a bat file and running that on a new clone of the repo.

The error is:
```
error CS0246: The type or namespace name 'Steamworks' could not be found (are you missing a using directive or an assembly reference?)
```

**How to reproduce**
- Import packages with dlls
```
"com.unity.netcode.gameobjects": "1.0.0-pre.6",
"com.community.netcode.transport.facepunch": "https://github.com/Unity-Technologies/multiplayer-community-contributions.git?path=/Transports/com.community.netcode.transport.facepunch"
```
- Run unity-builder action

I have created a public repo demonstrating this.
Repo: https://github.com/ottah/ReproSteamworks
Github action logs: https://github.com/ottah/ReproSteamworks/runs/5741999396#step:3:7393

There is also a `build.bat` that has the script I ran locally to test as well.

**Expected behavior**
Projects with plugins build.

**Additional details**

Any help on this would be appreciated. It could be the that Facepunch transport package is bundling their .dll's incorrectly, but since it is working in my existing build scripts I can't seem to figure out what is wrong.

**Comment by webbertakken** [comment]
Would you mind sharing what your solution was to this problem?

**Comment by ottah** [comment]
@webbertakken I gave up trying to fix it, we're just going to stick with our current CI/CD pipeline. I've made the repo public again if you want to check it out.

**Comment by Coada** [comment]
@webbertakken I am experiencing the exact same issue trying to build a Unity project with `game-ci/unity-builder@v2` that uses DOTween. The DLL is committed in the repository. Any suggestion how I can solve the build?

**Comment by spencer-cheng** [comment]
@webbertakken I am also experiencing the same issue. May I check if there is any progress on this part? Thanks.

**Comment by webbertakken** [comment]
Tweaking assembly references is tricky and I'm by no means an expert on this.

What I do know is that many people figured how to fix assembly references in their project (and got it working in CI) on our [discord](https://game.ci/discord).

If anyone has a fitting answer, it'd be helpful if they could share it here 🙂

**Comment by pippinmole** [comment]
I see this is specific to Steamworks. Assuming you are using Facepunch.Steamworks, instead of using the DLLs provided in the 'Releases' section of the github repository, use the source files. If you use Steamworks inside an asmdef, create an asmdef inside the Facepunch.Steamworks folder and reference this asmdef in the asmdef that uses this assembly.

If you have any issues let me know :)

**Comment by BenBonk** [comment]
If anyone comes across this through google like I did, and is looking for a fix for Facepunch.Steamworks, select your "Facepunch.Steamworks.Posix" file in the plugins folder, and set the OS under platform settings to Linux instead of OSX. This worked for me at least. 
![image](https://github.com/game-ci/unity-builder/assets/67299183/a64b6d02-798a-466d-b16d-137e9a8f02d9)
