### ISSUE TITLE
Mac OS build permission issue.

### ISSUE THREAD

**Issue by Ahtram** [game-ci/unity-builder#440]
**Bug description**
I still encounter the old permission issue when trying to run the StandaloneOSX build artifact executable.
![2022-09-20_15-53](https://user-images.githubusercontent.com/1751201/191201070-99df17d7-2e2d-42de-b145-2358aac4c3bd.png)
Which is relate to a closed issue #77 

Edit:
I cannot find how to solve the.

**Comment by webbertakken** [comment]
As far as I know `find -type f` only finds files, which are then piped into the exec clause. I don't see how recursing them will help. 

Could you please explain?

**Comment by Ahtram** [comment]
> 

Ok after further test. It doesn't actually solve the permission issue. 
Not sure why once it get compressed and download. It still doesn't get the +x permission.

**Comment by ManuelRauber** [comment]
> Ok after further test. It doesn't actually solve the permission issue.
> Not sure why once it get compressed and download. It still doesn't get the +x permission.

Because that's how GitHub Artifact Upload works: https://github.com/actions/upload-artifact#permission-loss

If you want to have the permissions, you have to create a TAR first and then use the upload-artifact action to upload the TAR.

**Comment by Ahtram** [comment]
> > Ok after further test. It doesn't actually solve the permission issue.
> > Not sure why once it get compressed and download. It still doesn't get the +x permission.
> 
> Because that's how GitHub Artifact Upload works: https://github.com/actions/upload-artifact#permission-loss
> 
> If you want to have the permissions, you have to create a TAR first and then use the upload-artifact action to upload the TAR.
> 
> See also here: [game-ci/unity-actions#152](https://github.com/game-ci/unity-actions/issues/152)

Thanks, I guess i'll give this a try. It looks promising.

**Comment by bella-cockrell** [comment]
I had this issue as well after I followed the Game CI [video tutorial](https://www.youtube.com/watch?v=M2BZr02uai0&feature=emb_title) in this run [here](https://github.com/bella-cockrell/unity-actions-fmod-poc/actions/runs/3854105447), and packaging up in a .tar worked for me as well.

I do have a 'This file can’t be opened because Apple cannot check it for malicious software' pop up, but I can successfully open it by right-clicking click > 'Open' > 'Open'. I imagine the issue here is because it is not [notarized](https://docs.unity3d.com/Manual/macos-building-notarization.html), so I will follow the instructions provided [here](https://game.ci/docs/github/deployment/ios)

**Comment by davidmfinol** [comment]
@bella-cockrell The instructions you linked are for iOS and not Mac. You may want to see https://github.com/game-ci/documentation/issues/262
