### ISSUE TITLE
Unclassified error occured while trying to activate license.

### ISSUE THREAD

**Issue by weisunglee** [game-ci/unity-builder#485]
**Bug description**

Hi, I got an error `Unclassified error occured while trying to activate license.` since yesterday.

```
---------- git config --list --show-origin -------------
file:/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:/etc/gitconfig	filter.lfs.required=true
file:/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
Changing to "/github/workspace/_activate-license~" directory.
/github/workspace/_activate-license~ /github/workspace
Requesting activation (personal license)
Unclassified error occured while trying to activate license.
Exit code was: 1
Error: The process '/usr/bin/docker' failed with exit code 1
```
I found a similar issue https://github.com/game-ci/unity-builder/issues/345 but it seems that didn't help with mine.

**How to reproduce**

Run build with 
```yaml
      - uses: game-ci/unity-builder@v2.1.2
        with:
          targetPlatform: WebGL          
```
then got the error.

-

**Expected behavior**

Successfully build.

**Additional details**

I had success before, but since yesterday it has been failing, I can't find the reason.

**Comment by vngupro** [comment]
Hi !

First, I'm sorry for any English mistake, it's not my first language.
I don't know if you had exactly the same problem as me and if you find a solution already.

A friend and I found out that the syntax you write in the yaml file is really strict if you want it to work with github actions.

Here's what we found :

- Do not add 2 newlines in succession.
- After `jobs:` do not add a newline.
- Align everything perfectly.
- For version, do not use syntax vmajor.minor.correction, use only vmajor i.e v3 and not v3.3.0
- A comment above an instruction is consider like a newline

There might be other syntax "tricks" but for now we only found this.

**Comment by madebyluque** [comment]
Hey @weisunglee ! Have you found a workaround for this error?

**Comment by segoja7** [comment]
Hi, I have the same error, there is a some fix?

**Comment by SeoulSKY** [comment]
I don't see the `env` block in your workflow. Did you add UNITY_LICENSE, UNITY_EMAIL and UNITY_PASSWORD?

**Comment by Soloveykos** [comment]
here is my variant, it's not working also: 
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          
used personal license and received:
Requesting activation (personal license)
Unclassified error occured while trying to activate license.
Exit code was: 1
Error: The process '/usr/bin/docker' failed with exit code 1

**Comment by Oknaa2** [comment]
`      
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion:  ${{ matrix.unityVersion }}
              
              `
              Mine looks like this, Same error. any fix ?

**Comment by GabLeRoux** [comment]
> Unclassified error occured while trying to activate license.

This usually happen when the wrong file was inserted into the `secrets.UNITY_LICENSE` env var.

There are a few related issues in the help threads on our discord too:

* https://discord.com/channels/710946343828455455/1159352860065157181
* https://discord.com/channels/710946343828455455/1155980604144365609

This usually happens when the activation process wasn't followed to the letter. (Ex; when the activation file content was pasted in `UNITY_LICENSE` instead of the actual license)

Refer to https://game.ci/docs/github/activation

Make sure that the content of your `UNITY_LICENSE` env var is the content of the downloaded license (in the`ulf` format, not `alf`).

The `alf` file is an _activation request file_ generated by Unity executable (usually from the [request activation file action](https://github.com/game-ci/unity-request-activation-file)) that needs to be uploaded to unity's website.

The ulf is the license you download from Unity's website.

## Detailed steps

Always refer [to documentation](https://game.ci/docs/github/activation) for most up to date procedures. Here's precise steps I took recently on a fork of a project where OP had same error:

1. Added `.github/workflows/activation.yml` from https://game.ci/docs/github/activation#personal-license
2. Ran manual workflow through Github > Actions > Acquire activation file
3. Downloaded `Unity_v2019.2.11f1.alf` from Summary page of `Acquire activation file` workflow
4. Deleted workflow run (to prevent others from downloading my activation request file)
5. Logged in to my Unity3d account on https://unity3d.com/
Followed instructions for Converting into a license here: https://game.ci/docs/github/activation#converting-into-a-license
 Did the trick about showing hidden activation section (I wish Unity didn't hide this...). Right now, you can't miss it, there's a big warning on GameCI's activation page.
6. Downloaded my license file (`Unity_v2019.x.ulf`
7. Visited `https://github.com/GabLeRoux/EmptyProject/settings/secrets/actions` (the project's Settings > Security > Secrets and variables > Actions) and Clicked 8. New repository secret button
9. Copied the content of downloaded license (`Unity_v2019.x.ulf`), I personally copy the content with `cat ~/downloads/Unity_v2019.x.ulf | pbcopy` on macOS to prevent any bad manipulation, but a good technique is to open the file in a vode editor such as Visual Studio Code and copy from here.
Name: `UNITY_LICENSE`
Secret: paste content of license (content of Unity_v2019.x.ulf), then hit Add secret
10. I went back to Actions > "Actions 😎" > clicked on the Job I previously cancelled and clicked on Re-run Jobs which re-runs the "Build my project ✨" job.

**Comment by AndrewKahr** [comment]
V4 has a new activation process so this should be resolved
