### ISSUE TITLE
Allow us to set Docker's Memory Usage

### ISSUE THREAD

**Issue by GitFlip** [game-ci/unity-builder#540]
**Context**

Within the `docker.ts` file there are two methods: `getLinuxCommand` and `getWindowsCommand` that return the `docker run` command string. There is no way for us to set the memory usage of this docker container that runs.

**Suggested solution**

Add `-m` argument to `docker run` command that takes an input from the Builder's Configuration Options. For example:

```yml
- uses: game-ci/unity-builder@v2
  with:
    dockerMemory: 4GB
```

**Considered alternatives**

Did not consider alternatives

**Additional details**

The reason for this is because when using a GitHub hosted Runner the VM has 7GB of RAM, and Unity Builder seems to think all of it is available to it - see snippet from Builder's log:
```
###########################
#    Building project     #
###########################

Unity Editor version:    2021.3.6f1 (7da38d85baf6)
Branch:                  2021.3/staging
Build type:              Release
Batch mode:              YES
System name:             Linux
Distro version:          #45-Ubuntu SMP Mon Apr 24 15:40:42 UTC 2023
Kernel version:          5.15.0-1038-azure
Architecture:            x86_64
Available memory:        6943 MB
```

The docker container however does not have that much memory and this causes the container to run out of memory when building giving an `Build failed, with exit code 137` because Unity Builder is trying to use more memory than what has been allocated to the container.

Adding the ability to set the memory allocation for the docker container will allow us to increase it to match what the Builder thinks is actually available.

**Comment by shubhank008** [comment]
Anything on this ?

**Comment by webbertakken** [comment]
Not sure if the proposed solution will work but we're always open to contributions! Counting on the community for this enhancement.

**Comment by wilg** [comment]
I mentioned this a while ago here https://github.com/game-ci/unity-builder/issues/432

**Comment by ejnarvala** [comment]
We are also seeing this issue when using our kubernetes ARSS GHA runners to process jobs. As part of this setup, we are using a docker-in-docker setup where each runner pod has a runner container and a DinD container with daemon exposed to the runner.

What we see is a similar issue where the unity app seems to be reporting the total memory of the VM/node that it's running in rather than the request/limit set for the DinD container. This leads to frequent OOMs (exit code 137). 

We have tried using the `dockerCpuLimit` and `dockerMemoryLimit` parameters, but this didn't seem to help. It only served to fix an invalid argument issue where not setting these values would result in this error:
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "9600000": write /sys/fs/cgroup/cpu,cpuacct/docker/286f35cb2ba3747ba53b449baea9a5a89632de7e218cd256a2d85b3c4e5fbd22/cpu.cfs_quota_us: invalid argument: unknown.
Error: Build failed with exit code 125
```

Our current best theory is this is related to this issue - https://github.com/moby/moby/issues/45378, but we have not been able to implement this fix successfully.

I'm wondering if there's any way to handle this on the game-ci side via some tweaks to the docker images or maybe something like an environment variable that tells unity the amount of memory it's allowed to use if such a thing exists.

**Comment by tebenkov2222** [comment]
Is there any solution to this problem? Is it possible to somehow limit uinty-builder's memory usage? When running pipelines in k8s, it takes the host data and not the set container limits. First it uses 4 gb and then asks for +10 and the pipeline crashes (although for the assembly of 4 GB our project is behind the scenes).

**Comment by webbertakken** [comment]
Replying to the last two comments regarding K8s:

There's generally speak two ways of limiting memory to a process
1. At the application level
2. At the OS / container level

For point 1:

Unity doesn't seem to have such a setting, to limit the amount of memory. Which makes sense because most of their rationale hasn't seem to involved CI much in the past years.

For point 2:

If you're runing the container on k8s, then you are in control of the container's runtime configuration.

To put things simply, you have two options that prevent OOM and allow you to properly schedule your pods:
1. To set resources.limits.memory and resources.requests.memory at the same amount. And set it slightly higher than the peak memory usage during your build. Consider using vertical pod autoscaler where useful.
2. Enforce hard memory cap and get into cgroups for fine-grained memory control

This first option will _just work_, the second has no guarantees. The reason for that is that you can't throttle memory the same way you can throttle cpu, since processes need immediate access to memory. 

When the kernel doesn't allocate more you risk the process being OOMKilled, which is highly likely to happen during the build process here.

Rationale to take away from said limitations: Before any fine-tuning, CI infrastructure should accommodate for running CI jobs, not vice versa. This is especially true if you have no control over the characteristics of the workload on application level.

**Comment by webbertakken** [comment]
Not reopening this issue because it doesn't describe a problem we can solve; if we were to add a flag that limited memory on container level, the container would simply crash because the OOM Killer would kill the main process.

Related resources:

- [Docker container resource constraints](https://docs.docker.com/engine/containers/resource_constraints/#understand-the-risks-of-running-out-of-memory)
- [Kubernetes Concept: Resource Management](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
- [Kubernetes API Reference: Pod](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/)
