### ISSUE TITLE
UNITY_LICENSE_FILE option removed to activate license

### ISSUE THREAD

**Issue by LevitatingKraken** [game-ci/unity-builder#593]
**Bug description**

Since commit caa0a81b47749f53714db4c5d77d6580c33fc3c1 UNITY_LICENSE_FILE option to activate unity is removed.
Is this intended? I still see in the code traces of "ulf" files.
What is the workaround for this?

**How to reproduce**

Run the latest gameci unity-builder with env var "UNITY_LICENSE_FILE" ulf file

**Expected behavior**

Running gameci with "UNITY_LICENSE_FILE" env var should activate the unity license

**Comment by AndrewKahr** [comment]
We were noticing increased failures in license activation via ULF in addition to Unity cutting off ULF creation. The change is in anticipation of v4 so the docs haven't been updated yet. Recommend staying on a tagged version rather than main for your workflows if there isn't a specific fix you need as main can have breaking changes like this without warning. To activate now, you'll need to pass your Unity email and password in addition to the license file for it to activate. You don't need a new license file either.
