### ISSUE TITLE
Missing Unity 6000.0.3f1 docker images

### ISSUE THREAD

**Issue by timcassell** [game-ci/unity-builder#652]
**Bug description**

unity-builder action fails with Unity 6000.0.3f1.

```Unable to find image 'unityci/editor:ubuntu-6000.0.3f1-linux-il2cpp-3' locally```

**Expected behavior**

unity-builder succeeds

**Additional details**

It looks like 6000.0.3 docker images don't exist.

**Comment by GabLeRoux** [comment]
To avoid any confusion, please note that **Unity 6 support is present with GameCI**. 

**The problem here is that it looks like updated the format of their page and our automated job to retrieve new versions don't see them anymore. 👀** 

We rely on their [releases/editor/archive page](https://unity.com/releases/editor/archive) and I can confirm that the following versions are listed there right now:

* 6000.0.4f1
* 6000.0.3f1

But our [Supported Editor Versions](https://game.ci/docs/docker/versions) page doesn't list them there.

We most likely need to update our [versioning-backend](https://github.com/game-ci/versioning-backend). Further investigation is necessary.

There was a [related discussion as well on Discord](https://discord.com/channels/710946343828455455/731513544490614845/1244859628559532075) which I tought was initially caused by Unity not updating their page, but since then, the version hasn't been seen by our automated system and The page style and organization really seem to have change since last time I checked.

**Comment by GabLeRoux** [comment]
The way it used to look like:
![CleanShot 2024-05-30 at 11 59 03](https://github.com/game-ci/unity-builder/assets/1264761/4c71f212-8363-46ab-8373-38bd830450fd)

How it looks like now:
![CleanShot 2024-05-30 at 11 59 04](https://github.com/game-ci/unity-builder/assets/1264761/a4e69ed6-3168-4a6b-bd80-ba595a6ba601)

Definitely, Unity changed something ;)
